apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mifrv5he9-nodejs-gitops
  description: This is GitOps manifest for mifrv5he9-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=mifrv5he9-nodejs
    backstage.io/kubernetes-id: mifrv5he9-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/mifrv5he9-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mifrv5he9-nodejs
