apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mifrv5he9-nodejs
  janus-idp.io/tekton: mifrv5he9-nodejs
  backstage.io/kubernetes-id: mifrv5he9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mifrv5he9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
